// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using 小專後端.Models;

#nullable disable

namespace 小專後端.Migrations
{
    [DbContext(typeof(englishContext))]
    partial class englishContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("list_items", b =>
                {
                    b.Property<int>("list_id")
                        .HasColumnType("int");

                    b.Property<int>("word_id")
                        .HasColumnType("int");

                    b.HasKey("list_id", "word_id")
                        .HasName("PK__list_ite__6C6150E1C3EAA6DD");

                    b.HasIndex("word_id");

                    b.ToTable("list_items");
                });

            modelBuilder.Entity("小專後端.Models.categories", b =>
                {
                    b.Property<int>("cid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cid"));

                    b.Property<string>("categories1")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("categories");

                    b.HasKey("cid")
                        .HasName("PK__categori__D837D05F9D3E6C6B");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("小專後端.Models.login_time", b =>
                {
                    b.Property<DateTime>("login_at")
                        .HasColumnType("datetime");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasIndex("user_id");

                    b.ToTable("login_time");
                });

            modelBuilder.Entity("小專後端.Models.personal_lists", b =>
                {
                    b.Property<int>("lid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("lid"));

                    b.Property<DateTime?>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("lid")
                        .HasName("PK__personal__DE105D079DE698F9");

                    b.HasIndex("user_id");

                    b.ToTable("personal_lists");
                });

            modelBuilder.Entity("小專後端.Models.problem_list", b =>
                {
                    b.Property<int>("pid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pid"));

                    b.Property<DateTime?>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("question_id")
                        .HasColumnType("int");

                    b.Property<int>("reporter_id")
                        .HasColumnType("int");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("pid")
                        .HasName("PK__problem___DD37D91AC81F40CA");

                    b.HasIndex("question_id");

                    b.HasIndex("reporter_id");

                    b.ToTable("problem_list");
                });

            modelBuilder.Entity("小專後端.Models.question_type", b =>
                {
                    b.Property<int>("tid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tid"));

                    b.Property<string>("question_type1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("question_type");

                    b.HasKey("tid")
                        .HasName("PK__question__DC105B0FF27D961C");

                    b.ToTable("question_type");
                });

            modelBuilder.Entity("小專後端.Models.questions", b =>
                {
                    b.Property<int>("qid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("qid"));

                    b.Property<string>("question_content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("question_correct")
                        .HasColumnType("int");

                    b.Property<int>("question_error")
                        .HasColumnType("int");

                    b.Property<int>("question_type_id")
                        .HasColumnType("int");

                    b.Property<int>("word_id")
                        .HasColumnType("int");

                    b.HasKey("qid")
                        .HasName("PK__question__C277C221E720D568");

                    b.HasIndex("question_type_id");

                    b.HasIndex("word_id");

                    b.ToTable("questions");
                });

            modelBuilder.Entity("小專後端.Models.quiz_detail_logs", b =>
                {
                    b.Property<int>("quiz_record_id")
                        .HasColumnType("int");

                    b.Property<int>("question_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_wrong")
                        .HasColumnType("bit");

                    b.Property<TimeOnly>("time_taken")
                        .HasColumnType("time");

                    b.Property<string>("user_answer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("quiz_record_id", "question_id")
                        .HasName("PK__quiz_det__64E3720A8066BD3F");

                    b.HasIndex("question_id");

                    b.ToTable("quiz_detail_logs");
                });

            modelBuilder.Entity("小專後端.Models.quiz_error_option", b =>
                {
                    b.Property<int>("quiz_record_id")
                        .HasColumnType("int");

                    b.Property<int>("question_id")
                        .HasColumnType("int");

                    b.Property<int>("option_word_id")
                        .HasColumnType("int");

                    b.HasKey("quiz_record_id", "question_id", "option_word_id")
                        .HasName("PK__quiz_err__D17D6CABC35F45B7");

                    b.HasIndex("option_word_id");

                    b.HasIndex("question_id", "option_word_id");

                    b.ToTable("quiz_error_option");
                });

            modelBuilder.Entity("小專後端.Models.quiz_records", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("correct_count")
                        .HasColumnType("int");

                    b.Property<DateTime?>("quiz_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<byte>("source")
                        .HasColumnType("tinyint");

                    b.Property<TimeOnly>("total_time_spent")
                        .HasColumnType("time");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.Property<int>("wrong_count")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK__quiz_rec__3213E83F36D5D1B4");

                    b.HasIndex("user_id");

                    b.ToTable("quiz_records");
                });

            modelBuilder.Entity("小專後端.Models.users", b =>
                {
                    b.Property<int>("uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("uid"));

                    b.Property<string>("anchcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("uid")
                        .HasName("PK__users__DD701264FB198B0D");

                    b.ToTable("users");
                });

            modelBuilder.Entity("小專後端.Models.words", b =>
                {
                    b.Property<int>("wid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("wid"));

                    b.Property<string>("KK")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("categories_id")
                        .HasColumnType("int");

                    b.Property<byte>("difficulty_level")
                        .HasColumnType("tinyint");

                    b.Property<string>("meaning")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("parts_of_speech")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("spelling")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("wid")
                        .HasName("PK__words__30F153BBC77FB6E0");

                    b.HasIndex("categories_id");

                    b.ToTable("words");
                });

            modelBuilder.Entity("list_items", b =>
                {
                    b.HasOne("小專後端.Models.personal_lists", null)
                        .WithMany()
                        .HasForeignKey("list_id")
                        .IsRequired()
                        .HasConstraintName("FK_list_items_personal_lists");

                    b.HasOne("小專後端.Models.words", null)
                        .WithMany()
                        .HasForeignKey("word_id")
                        .IsRequired()
                        .HasConstraintName("FK_list_items_words");
                });

            modelBuilder.Entity("小專後端.Models.login_time", b =>
                {
                    b.HasOne("小專後端.Models.users", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .IsRequired()
                        .HasConstraintName("FK_login_time_users");

                    b.Navigation("user");
                });

            modelBuilder.Entity("小專後端.Models.personal_lists", b =>
                {
                    b.HasOne("小專後端.Models.users", "user")
                        .WithMany("personal_lists")
                        .HasForeignKey("user_id")
                        .IsRequired()
                        .HasConstraintName("FK_personal_lists_users");

                    b.Navigation("user");
                });

            modelBuilder.Entity("小專後端.Models.problem_list", b =>
                {
                    b.HasOne("小專後端.Models.questions", "question")
                        .WithMany("problem_list")
                        .HasForeignKey("question_id")
                        .IsRequired()
                        .HasConstraintName("FK_problem_list_questions");

                    b.HasOne("小專後端.Models.users", "reporter")
                        .WithMany("problem_list")
                        .HasForeignKey("reporter_id")
                        .IsRequired()
                        .HasConstraintName("FK_problem_list_users");

                    b.Navigation("question");

                    b.Navigation("reporter");
                });

            modelBuilder.Entity("小專後端.Models.questions", b =>
                {
                    b.HasOne("小專後端.Models.question_type", "question_type")
                        .WithMany("questions")
                        .HasForeignKey("question_type_id")
                        .IsRequired()
                        .HasConstraintName("FK_questions_question_type");

                    b.HasOne("小專後端.Models.words", "word")
                        .WithMany("questions")
                        .HasForeignKey("word_id")
                        .IsRequired()
                        .HasConstraintName("FK_questions_words");

                    b.Navigation("question_type");

                    b.Navigation("word");
                });

            modelBuilder.Entity("小專後端.Models.quiz_detail_logs", b =>
                {
                    b.HasOne("小專後端.Models.questions", "question")
                        .WithMany("quiz_detail_logs")
                        .HasForeignKey("question_id")
                        .IsRequired()
                        .HasConstraintName("FK_quiz_detail_logs_questions");

                    b.HasOne("小專後端.Models.quiz_records", "quiz_record")
                        .WithMany("quiz_detail_logs")
                        .HasForeignKey("quiz_record_id")
                        .IsRequired()
                        .HasConstraintName("FK_quiz_detail_logs_quiz_records");

                    b.Navigation("question");

                    b.Navigation("quiz_record");
                });

            modelBuilder.Entity("小專後端.Models.quiz_error_option", b =>
                {
                    b.HasOne("小專後端.Models.words", "option_word")
                        .WithMany("quiz_error_option")
                        .HasForeignKey("option_word_id")
                        .IsRequired()
                        .HasConstraintName("FK_quiz_error_option_words");

                    b.HasOne("小專後端.Models.quiz_detail_logs", "quiz_detail_logs")
                        .WithMany("quiz_error_optionquiz_detail_logs")
                        .HasForeignKey("question_id", "option_word_id")
                        .IsRequired()
                        .HasConstraintName("FK_quiz_error_option_quiz_detail_logs1");

                    b.HasOne("小專後端.Models.quiz_detail_logs", "quiz_detail_logsNavigation")
                        .WithMany("quiz_error_optionquiz_detail_logsNavigation")
                        .HasForeignKey("quiz_record_id", "question_id")
                        .IsRequired()
                        .HasConstraintName("FK_quiz_error_option_quiz_detail_logs");

                    b.Navigation("option_word");

                    b.Navigation("quiz_detail_logs");

                    b.Navigation("quiz_detail_logsNavigation");
                });

            modelBuilder.Entity("小專後端.Models.quiz_records", b =>
                {
                    b.HasOne("小專後端.Models.users", "user")
                        .WithMany("quiz_records")
                        .HasForeignKey("user_id")
                        .IsRequired()
                        .HasConstraintName("FK_quiz_records_users");

                    b.Navigation("user");
                });

            modelBuilder.Entity("小專後端.Models.words", b =>
                {
                    b.HasOne("小專後端.Models.categories", "categories")
                        .WithMany("words")
                        .HasForeignKey("categories_id")
                        .IsRequired()
                        .HasConstraintName("FK_words_categories");

                    b.Navigation("categories");
                });

            modelBuilder.Entity("小專後端.Models.categories", b =>
                {
                    b.Navigation("words");
                });

            modelBuilder.Entity("小專後端.Models.question_type", b =>
                {
                    b.Navigation("questions");
                });

            modelBuilder.Entity("小專後端.Models.questions", b =>
                {
                    b.Navigation("problem_list");

                    b.Navigation("quiz_detail_logs");
                });

            modelBuilder.Entity("小專後端.Models.quiz_detail_logs", b =>
                {
                    b.Navigation("quiz_error_optionquiz_detail_logs");

                    b.Navigation("quiz_error_optionquiz_detail_logsNavigation");
                });

            modelBuilder.Entity("小專後端.Models.quiz_records", b =>
                {
                    b.Navigation("quiz_detail_logs");
                });

            modelBuilder.Entity("小專後端.Models.users", b =>
                {
                    b.Navigation("personal_lists");

                    b.Navigation("problem_list");

                    b.Navigation("quiz_records");
                });

            modelBuilder.Entity("小專後端.Models.words", b =>
                {
                    b.Navigation("questions");

                    b.Navigation("quiz_error_option");
                });
#pragma warning restore 612, 618
        }
    }
}
